### PR TITLE
Add a global menu for global actions

### PR DESCRIPTION
**Pull request by wandernauta**
Adds a hamburger button to the zoom overlay (which is now called the
button overlay) that shows a dropdown (context) menu when clicked.

The menu only has a Quit action at present, but this is where the New, Open,
Save and Save As actions from #155 would go.

### CODE REVIEW

**Comment by comonoidial** [comment]
Quick note, it might be handy to add the inspector and debug mode to this menu too.

**Comment by comonoidial** [comment]
Quick note, the current implementation seems to block all mouse actions across the entire top row of the screen for about 40 pixels.

**Comment by wandernauta** [comment]
@comonoidial Yep. There's two ways to fix this:

- Give the top bar some kind of background to indicate that there's going to be more buttons on there (there aren't many yet, but there might be).
- Set the top bar mouse transparent so that it no longer catches mouse events.

**Comment by comonoidial** [comment]
Setting the bar mouse transparent also disables the button, and I don't like reducing screen space.
So I guess these flowpanes should be replaces by gridpanes instead.

**Comment by wandernauta** [comment]
I'm not sure gridpane fits. I thought there was a way to tell flowpane to shrink to its contents; probably some magic incantation with `minWidth`, `prefWidth`, `maxWidth` etc

**Pull request merged**
