### PR TITLE
fixed fullscreen mode for all platforms.

### PR DESCRIPTION
**Pull request by TheMSB**
Fullscreen mode should now work correctly on all platforms.

### CODE REVIEW

**Comment by wandernauta** [comment]
Would this work on machines with multiple screens, for example in the touchscreen?

**Comment by TheMSB** [comment]
> Would this work on machines with multiple screens, for example in the touchscreen?

According to the java documentation: If the platform supports multiple screens an application can control which Screen the Stage will enter full-screen mode on by setting its position to be within the bounds of that Screen prior to entering full-screen mode.

**Comment by wandernauta** [comment]
I'd guess this would show the app fullscreen on the primary display, that is, the laptop screen, with no option of moving it to the touchscreen.

**Comment by TheMSB** [comment]
> I'd guess this would show the app fullscreen on the primary display, that is, the laptop screen, with no option of moving it to the touchscreen.

It depends on which screen you launch the app from, on OSX for example I can always exit fullscreen mode and just move the app to another display if I so choose.

**Comment by wandernauta** [comment]
Yes, but the touchscreen doesn't run on OS X, it runs on Windows.

**Comment by TheMSB** [comment]
> Yes, but the touchscreen doesn't run on OS X, it runs on Windows.

You can then still choose to launch the app from the external display if you want, If launching from eclipse: just drag eclipse into the external screen and then run it.

**Comment by wandernauta** [comment]
I've got an idea. Why not add a button to toggle fullscreen, say, F11? The program would start windowed, you could drag it to the screen you want, then hit F11.

**Comment by TheMSB** [comment]
> I've got an idea. Why not add a button to toggle fullscreen, say, F11? The program would start windowed, you could drag it to the screen you want, then hit F11.

I'm not against the idea, I want to run a little test though.

**Comment by TheMSB** [comment]
I will put this PR on a back burner, will implement a visual button for fullscreen to make a toggle.

**Comment by TheMSB** [comment]
Ran into a genuine Java error after playing around with this for a bit. Not sure what triggers it exactly but it happens when I toggle maximised and fullscreen alternating a couple of times.

2015-05-06 07:01:11.544 java[8111:507] *** -[__NSArrayM objectAtIndex:]: index 2 beyond bounds [0 .. 1]
2015-05-06 07:01:11.546 java[8111:507] (
	0   CoreFoundation                      0x00007fff909e125c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff93d6be75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff908bf4f5 -[__NSArrayM objectAtIndex:] + 245
	3   AppKit                              0x00007fff90d97b44 -[NSView performKeyEquivalent:] + 118
	4   AppKit                              0x00007fff90d97ab3 -[NSView _performKeyEquivalent:conditionally:] + 180
	5   AppKit                              0x00007fff90d97989 -[NSWindow performKeyEquivalent:] + 61
	6   libglass.dylib                      0x00000001ddb6e633 -[GlassWindow_Normal performKeyEquivalent:] + 67
	7   AppKit                              0x00007fff90d97772 -[NSApplication _handleKeyEquivalent:] + 455
	8   AppKit                              0x00007fff90d06acc -[NSApplication sendEvent:] + 3293
	9   AppKit                              0x00007fff90b569f9 -[NSApplication run] + 646
	10  libglass.dylib                      0x00000001ddb4ff47 -[GlassApplication runLoop:] + 1783
	11  Foundation                          0x00007fff9495f7ce __NSThreadPerformPerform + 229
	12  CoreFoundation                      0x00007fff909125b1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	13  CoreFoundation                      0x00007fff90903c62 __CFRunLoopDoSources0 + 242
	14  CoreFoundation                      0x00007fff909033ef __CFRunLoopRun + 831
	15  CoreFoundation                      0x00007fff90902e75 CFRunLoopRunSpecific + 309
	16  java                                0x0000000104c9b490 CreateExecutionEnvironment + 871
	17  java                                0x0000000104c9721c JLI_Launch + 1952
	18  java                                0x0000000104c9d4ed main + 101
	19  java                                0x0000000104c96a74 start + 52
)

**Comment by wandernauta** [comment]
Ooh, scary.

**Comment by i3anaan** [comment]
What is the status of this PR?

**Comment by TheMSB** [comment]
This PR is non-essential, I designed this at the time to prevent the crashing of OSX, since it used keyboard commands it seems that this is unneeded/unwanted functionality since we are building for touch.

**Pull request closed without merging**
