### PR TITLE
Rewrite the change propagation logic

### PR DESCRIPTION
**Pull request by comonoidial**
This is attempt to make the change update and propagation logic saner and more correct.
While this improve some of the problems in #188, weird bugs still happen within function block types.
Also depends on PR #210

### CODE REVIEW

**Comment by wandernauta** [comment]
Can you elaborate a bit on how (why) this works? If I read the diff correctly, `connectionState` is gone, `exprIsDirty` stays, and what used to be `visualState` is now a single observable boolean `staleVisuals` (not `visualsAreStale`). Touching the staleVisuals bit re'draws' components. So far so good.

However, from what I can tell, changes seem to be propagated both 'up' and 'down'. How do you avoid (infinite) loops? Doesn't this cause more redraws than necessary?

**Comment by comonoidial** [comment]
How can this produce merge conflicts?
This just is based on pr210 merged with yesterday's master...

**Comment by wandernauta** [comment]
It should be a breeze to rebase then. If you're not comfortable rebasing I can just manually merge it for you.

**Comment by comonoidial** [comment]
I think issue #188 is fully resolved now, and also made updating and typechecking even less frequent.
rebasing? why can't git take history in account properly when merging...

**Comment by wandernauta** [comment]
Merged.

**Pull request merged**
