### PR TITLE
Set minimum window size to 800x600

### PR DESCRIPTION
**Pull request by jjkester**

### CODE REVIEW

**Comment by wandernauta** [comment]
I could be wrong, but I do not believe that this is correct. The minimum and maximum size for the tactile pane are set to be exactly equal to prevent the pane from resizing itself depending on its contents. To change the window size, try the minimum and maximum sizes of the Stage (window).

**Comment by jjkester** [comment]
Fixed.

**Comment by wandernauta** [comment]
Looks and works great. Can you give this a quick rebase?

**Comment by jjkester** [comment]
Rebased.

**Comment by wandernauta** [comment]
Marvelous! Thanks.

**Pull request merged**
