### PR TITLE
Let Expr cache expressions

### PR DESCRIPTION
**Pull request by jjkester**
Part of #112.

Also fixes InspectorWindow to not (possibly) modify types when UI calls type checker correctly.

### CODE REVIEW

**Comment by jjkester** [comment]
This is without the UI stuff.

**Comment by wandernauta** [comment]
Would you like to have this merged into `master`, `demo` or neither?

**Comment by jjkester** [comment]
I think master is fine, as this is just a preparation for UI fixes.

The slight improvement of the inspector window is not that important for the demo either.

**Comment by wandernauta** [comment]
Seems to work, will merge into `master`. Thanks! :+1:

**Pull request merged**
