### PR TITLE
Simplify the fxml of Display/Value/Slider-Blocks

### PR DESCRIPTION
**Pull request by comonoidial**

### CODE REVIEW

**Comment by wandernauta** [comment]
This PR (again) changes the appearance of some blocks - ValueBlock and DisplayBlock have some extra padding now, but SliderBlock doesn't. Is that intentional?

**Comment by comonoidial** [comment]
Not sure where that padding comes from, and its not so important before #243.

**Comment by comonoidial** [comment]
I will stop adding things to this PR, even though lots of ugliness is left.

**Comment by Flumble** [comment]
The padding in the display and value blocks appears because the nodes inside are smaller than the block and they get tucked together in the middle.
I approve of the changes and have some additional ones:

**Comment by wandernauta** [comment]
Which additional ones? You have my curiousity

**Comment by comonoidial** [comment]
@Flumble this has some minor conflicts due to merging of #272.

**Comment by Flumble** [comment]
The conflicts are resolved now.

**Pull request merged**
