### PR TITLE
Split Defintion block into a inner and outer part 

### PR DESCRIPTION
**Pull request by comonoidial**
Also types now only propagate outwards from a lambda.
Depends on #260.

### CODE REVIEW

**Comment by wandernauta** [comment]
This change seems to have shifted the anchors a few hundred px:

screenshot

**Comment by comonoidial** [comment]
Yes, internal anchors are now centered because it looks ugly and unexpected on the left side.

**Comment by wandernauta** [comment]
I'll assign this PR to @Flumble because it contains visual changes, as discussed.

**Comment by wandernauta** [comment]
Fantastic! Merged. :sparkles:

**Pull request merged**
