### PR TITLE
Attempt to make the UI look a little more subtle

### PR DESCRIPTION
**Pull request by comonoidial**
Just details, mostly to experiment with how javafx works.

### CODE REVIEW

**Comment by wandernauta** [comment]
Interesting. Do the rounded borders have a special meaning?

**Comment by comonoidial** [comment]
Not yet, but possibly is block shape nice to use to distinguish between various kinds, and then pure functions/values should have a minimalistic shape.

**Comment by wandernauta** [comment]
Hmm. I've got the same doubts here that I have about #158 and #194. Every visual element or visual distinction we introduce increases the size of Viskell's vocabulary. For example, `ValueBlock` here has rounded corners and reduced padding, but `DisplayBlock` doesn't. You'd have to explain why they look different to every single user, in some way or other.

**Comment by comonoidial** [comment]
In this case it is not the intention to increase the Viskell's vocabulary.
It is part of a larger experiment I want to do for increasing readability of larger programs, where instead of keeping everything uniform, subtle meaningful variations in visual style are used to subconsciously guide you through a program (these variations have no effect on the generated code).

That displayblock's and co look differently is in my opinion beneficial as they are not really part of the program, but merely observers/debugging helpers of the program.

As for the other mentioned issues, Viskell is now extremely minimal from the syntactical point of view, especially compared to textual languages.
And I think while a visual language needs to have a lot less constructs than a textual one, specializing the most common constructs will help readability by avoiding being a big blob of identical blocks and wires.

**Comment by comonoidial** [comment]
This PR is an outdated mix of things on issues that require a more thorough redesign.

**Pull request closed without merging**
