### PR TITLE
Report: Improve title page

### PR DESCRIPTION
**Pull request by wandernauta**

### CODE REVIEW

**Comment by TheMSB** [comment]
Looks great, can I suggest maybe adding the eye logo to the cover image? Otherwise this looks awesome.

**Comment by i3anaan** [comment]
Agree with the eye icon

**Comment by wandernauta** [comment]
Added eye image.

**Comment by TheMSB** [comment]
I originally meant in the orange image but this looks good.

**Comment by wandernauta** [comment]
Great! I'll give it a merge then. Thanks for taking a look @TheMSB.

**Pull request merged**
