### PR TITLE
Add Hindley-Milner example image

### PR DESCRIPTION
**Pull request by wandernauta**

### CODE REVIEW

**Comment by jjkester** [comment]
I do not really like the image, the style does not match anything. Is this fixable (for example text in same font, etc.)?

**Comment by wandernauta** [comment]
I believe I still have the SVG file.

**Comment by wandernauta** [comment]
Yep, I still have the SVG.

**Comment by wandernauta** [comment]
I have the SVG, but changing the font makes Inkscape panic over the use of Greek. I'll close this for now.

**Pull request closed without merging**
